id: IC149DD17
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:54:28.784370'
last_modified: '2022-05-30T22:54:28.784382'
parser: null
source_metadata:
  title: Rangrik Dorje Series
  language: en
  description: 'Texts by and about the treasure-revealer Rangrik Dorje (rang rig rdo
    rje) alias Kusum Lingpa (sku gsum gling pa, 1847–1903) of Nyarong:'
  volume:
    fDD14:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      base_file: fDD14.txt
      order: 1
      parent: Guru Rinpoche Prayers
    f9CBB:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      base_file: f9CBB.txt
      order: 2
      parent: Guru Rinpoche Prayers
    fBE15:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      base_file: fBE15.txt
      order: 3
      parent: Guru Rinpoche Prayers
    fE54E:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      base_file: fE54E.txt
      order: 4
      parent: Guru Rinpoche Prayers
    f2CE0:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      base_file: f2CE0.txt
      order: 5
      parent: Guru Rinpoche Prayers
    f01BF:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      base_file: f01BF.txt
      order: 6
      parent: Guru Rinpoche Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
